import Head from "next/head";
import NavBar from "@/components/navbar/Navbar";
import {Container} from "@nextui-org/react";

export default function Merchants() {
  return (
    <>
      <Head>
        <title>BulkMagic Languages Dashboard</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <NavBar location={"languages"}/>
      <Container sm>
        <h1>Languages</h1>
      </Container>
    </>
  );
}
