import Head from "next/head";
import {Container, Text, Input, Card, Spacer, Button, Loading} from "@nextui-org/react";
import {useState} from "react";
import {useRouter} from "next/router";
import PhoneInput from "react-phone-input-2";
import "react-phone-input-2/lib/high-res.css";
import {useSessionStore} from "@/components/store/session";
import {loginAdmin} from "@/utils/accessServices";
import {toast} from "react-hot-toast";

export default function Home() {
  const {logIn} = useSessionStore();
  const [form, setForm] = useState({
    email: "",
    password: "",
    phone: ""
  });
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleFormSubmit = () => {
    setLoading(true);
    console.log(form);
    loginAdmin(form)
      .then(r => {
        console.log(r);
        logIn({
          id: r.data.user._id,
          email: r.data.user.email,
          name: r.data.user.username,
          phone: r.data.user.phone,
          accessToken: r.data.accessToken,
          refreshToken: r.data.refreshToken
        })
        toast.success("Login Successful")
        setTimeout(() => {
        router.push("/admin")
        }, 1000)
      })
      .catch(e => {
        console.log(e);
        setLoading(false);
        return toast.error(e?.response?.data?.message)
      });
  };

  const handleFormChange = (e: any) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value
    });
  };

  const handlePhoneNumberChange = (value: string, country: any) => {
    const index = country.dialCode.length;
    setForm({
      ...form,
      phone: `+${value.slice(0, index)}-${value.slice(index)}`
    });
  };

  return (
    <form>
      <Head>
        <title>BulkMagic Admin Login</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Container
        css={{
          height: "100vh"
        }}
        direction={"column"}
        display={"flex"}
        justify={"center"}
        alignItems={"center"}>
        <Container xs>
          <Card>
            <Card.Body>
              <Text h2>BulkMagic Admin Panel</Text>
              <Text h3>Please login to continue</Text>
              <Spacer y={1}/>
              <Input
                name={"email"}
                onChange={(e) => handleFormChange(e)}
                fullWidth
                clearable
                label={"Email"}/>
              <Spacer y={1.5}/>
              <Text>
                Phone Number
              </Text>
              <PhoneInput
                inputStyle={{
                  border: "2px solid #d9d9d9",
                  borderRadius: "15px",
                  width: "100%",
                  background: "white",
                  fontWeight: "400",
                  height: "45px",
                  fontSize: "14px",
                }}
                buttonStyle={{
                  border: "2px solid #d9d9d9",
                  borderRadius: "15px 0 0 15px",
                }}
                country="us"
                inputProps={{
                  name: "phone",
                  required: true,
                  autoFocus: true
                }}
                autoFormat={false}
                value={form.phone}
                onChange={handlePhoneNumberChange}
              />
              <Spacer y={1.5}/>
              <Input.Password
                name={"password"}
                onChange={(e) => handleFormChange(e)}
                fullWidth
                clearable
                label={"Password"}/>
              <Spacer y={1.5}/>
              <Button disabled={!!loading} onPress={() => handleFormSubmit()}>
                {!loading ? "Login" : <Loading type="points" color="currentColor" size="sm"/>}
              </Button>
            </Card.Body>
          </Card>
        </Container>
      </Container>
    </form>
  );
}
