import Head from "next/head";
import {Container, Text, Input, Card, Spacer, Button, Loading} from "@nextui-org/react";
import {useState} from "react";
import {useRouter} from "next/router";
import PhoneInput from "react-phone-input-2";
import "react-phone-input-2/lib/high-res.css";
import {useSessionStore} from "@/components/store/session";

export default function Home() {
  const {logIn} = useSessionStore();
  const [form, setForm] = useState({
    email: "",
    password: "",
    phone: ""
  });
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleFormSubmit = () => {
    setLoading(true);
    logIn({
      id: "1",
      email: form.email,
      name: "NOMBRE HARDCODE",
      phone: form.phone,
      accessToken: "123",
      refreshToken: "123"
    });
  localStorage.setItem("user", JSON.stringify(form));
  router.push("/admin");
};

const handleFormChange = (e: any) => {
  setForm({
    ...form,
    [e.target.name]: e.target.value
  });
};

return (
  <form>
    <Head>
      <title>BulkMagic Admin Login</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <Container
      css={{
        height: "100vh"
      }}
      direction={"column"}
      display={"flex"}
      justify={"center"}
      alignItems={"center"}>
      <Container xs>
        <Card>
          <Card.Body>
            <Text h2>BulkMagic Admin Panel</Text>
            <Text h3>Please login to continue</Text>
            <Spacer y={1}/>
            <Input
              name={"email"}
              onChange={(e) => handleFormChange(e)}
              fullWidth
              clearable
              label={"Email"}/>
            <Spacer y={1.5}/>
            <Text>
              Phone Number
            </Text>
            <PhoneInput
              inputStyle={{
                border: "2px solid #d9d9d9",
                borderRadius: "15px",
                width: "100%",
                background: "white",
                fontWeight: "400",
                height: "45px",
                fontSize: "14px",
              }}
              buttonStyle={{
                border: "2px solid #d9d9d9",
                borderRadius: "15px 0 0 15px",
              }}
              country="us"
              inputProps={{
                name: "phone",
                required: true,
                autoFocus: true
              }}
              autoFormat={false}
              onChange={(e) => {
                setForm({
                  ...form,
                  phone: e
                });
              }}
            />
            <Spacer y={1.5}/>
            <Input.Password
              name={"password"}
              onChange={(e) => handleFormChange(e)}
              fullWidth
              clearable
              label={"Password"}/>
            <Spacer y={1.5}/>
            <Button onPress={() => handleFormSubmit()}>
              {!loading ? "Login" : <Loading type="points" color="currentColor" size="sm"/>}
            </Button>
          </Card.Body>
        </Card>
      </Container>
    </Container>
  </form>
);
}
