import Head from "next/head";
import NavBar from "@/components/navbar/Navbar";
import {Container, Table, Text, Spacer, Checkbox, Grid, Input, Row, Button} from "@nextui-org/react";


export default function Merchants() {
  return (
    <>
      <Head>
        <title>BulkMagic Buyers Dashboard</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <NavBar location={"buyers"}/>
      <Container sm>
        <Spacer y={1}/>
        <Text h1>Buyers Management</Text>
        <Text h2>Filters:</Text>
        <Spacer y={1}/>
        <Grid.Container gap={1} justify="center" alignItems="center">
          <Grid>
            <Container>
              <Row>
                <Checkbox.Group orientation="horizontal">
                  <Checkbox value="">
                    Country Code
                  </Checkbox>
                </Checkbox.Group>
                <Input size="sm" width="60px"/>
              </Row>
              <Text h5>
                (no need to include &#34;+&#34;)
              </Text>
            </Container>
          </Grid>
          <Grid>
            <Container>
              <Row>
                <Checkbox.Group orientation="horizontal">
                  <Checkbox value="">
                    Recent Signups
                  </Checkbox>
                </Checkbox.Group>
              </Row>
              <Text h5>
                (default is chronological)
              </Text>
            </Container>
          </Grid>
          <Grid>
            <Container>
              <Row>
                <Checkbox.Group orientation="horizontal">
                  <Checkbox value="">
                    Largest Transactions
                  </Checkbox>
                </Checkbox.Group>
              </Row>
              <Text h5>
                (try it to pair with &#34;Country Code&#34;)
              </Text>
            </Container>
          </Grid>
          <Grid>
            <Button>
              Search
            </Button>
          </Grid>
        </Grid.Container>
        <Spacer y={1}/>
        <Table
          lined
          color="primary"
          aria-label="Example pagination table3"
          css={{
            height: "auto",
            minWidth: "100%",
          }}
        >
          <Table.Header>
            <Table.Column align="center">Store ID</Table.Column>
            <Table.Column align="center">Country Code</Table.Column>
            <Table.Column align="center">Phone Number</Table.Column>
            <Table.Column align="center">Email Address</Table.Column>
            <Table.Column align="center">Store Name</Table.Column>
            <Table.Column align="center">Transaction Totals (Local Currency)</Table.Column>
          </Table.Header>
          <Table.Body>
            <Table.Row key="1">
              <Table.Cell>082</Table.Cell>
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>marcelo.godoy@mi.unc.edu.ar</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
              <Table.Cell>$567054.34</Table.Cell>
            </Table.Row>
            <Table.Row key="2">
              <Table.Cell>082</Table.Cell>
              <Table.Cell>+54</Table.Cell>
              <Table.Cell>3517630330</Table.Cell>
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
              <Table.Cell>$567054.34</Table.Cell>
            </Table.Row>
            <Table.Row key="3">
              <Table.Cell>082</Table.Cell>
              <Table.Cell>+54</Table.Cell>
              <Table.Cell>3517630330</Table.Cell>
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
              <Table.Cell>$567054.34</Table.Cell>
            </Table.Row>
            <Table.Row key="4">
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>3517630330</Table.Cell>
              <Table.Cell>marcelo.godoy@mi.unc.edu.ar</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
              <Table.Cell>$567054.34</Table.Cell>
            </Table.Row>
            <Table.Row key="5">
              <Table.Cell>082</Table.Cell>
              <Table.Cell>+54</Table.Cell>
              <Table.Cell>3517630330</Table.Cell>
              <Table.Cell>marcelo.godoy@mi.unc.edu.ar</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
              <Table.Cell>$567054.34</Table.Cell>
            </Table.Row>
            <Table.Row key="6">
              <Table.Cell>082</Table.Cell>
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>marcelo.godoy@mi.unc.edu.ar</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
              <Table.Cell>$567054.34</Table.Cell>
            </Table.Row>
            <Table.Row key="7">
              <Table.Cell>082</Table.Cell>
              <Table.Cell>+54</Table.Cell>
              <Table.Cell>3517630330</Table.Cell>
              <Table.Cell>marcelo.godoy@mi.unc.edu.ar</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
              <Table.Cell>$567054.34</Table.Cell>
            </Table.Row>
            <Table.Row key="8">
              <Table.Cell>082</Table.Cell>
              <Table.Cell>+54</Table.Cell>
              <Table.Cell>3517630330</Table.Cell>
              <Table.Cell>marcelo.godoy@mi.unc.edu.ar</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
              <Table.Cell>$567054.34</Table.Cell>
            </Table.Row>
          </Table.Body>
          <Table.Pagination
            shadow
            noMargin
            align="center"
            rowsPerPage={7}
            onPageChange={(page) => console.log({page})}
          />
        </Table>
        <Spacer y={1}/>
        <Container sm display="flex" alignItems="flex-end" justify="flex-end">
          <Text h3>
            Total Sum of Transactions: $3,936,380.38
          </Text>
        </Container>
      </Container>
    </>
  );
}
