import Head from "next/head";
import NavBar from "@/components/navbar/Navbar";
import {
  Container,
  Table,
  Text,
  Spacer,
  Checkbox,
  Grid,
  Input,
  Row,
  Button,
  Pagination,
  Loading
} from "@nextui-org/react";
import {useRouter} from "next/router";
import {GetServerSideProps} from "next";
import useSWR, {SWRConfig} from "swr";
export const getServerSideProps: GetServerSideProps = async (context) => {
  const page = context.query.page || 1;
  const res = await fetch(`http://localhost:3000/api/admin/listBuyers?page=${page}&limit=10`);
  const data = await res.json();
  return {
    props: {
      fallback: {
        "http://localhost:3000/api/admin/listMerchants?page=1&limit10": data
      }
    }
  };
};

interface data {
  userId: number;
  id: number;
  email: string;
  username: string;
  phone: string;
  total: number;
}

function DataTable({page}: { page: string | string[] | number | number[] | undefined }) {
  const router = useRouter();
  const fetcher = (url: string) => fetch(url).then((res) => res.json());
  const {
    data,
    isLoading
  } = useSWR(`http://localhost:3000/api/admin/listBuyers?page=${page}&limit=10`, fetcher, {refreshInterval: 20000});
  console.log(data)
  if (isLoading) {
    return (
      <Container xl display="flex" alignItems="center" justify="center">
        <Spacer y={10}/>
        <Loading size="xl" type="points">
          Loading Table
        </Loading>
      </Container>
    );
  }
  return (
    <>
      <Table
        lined
        color="primary"
        aria-label="Example pagination table"
        css={{
          height: "auto",
          minWidth: "100%",
        }}
      >
        <Table.Header>
          <Table.Column align="center">Country Code</Table.Column>
          <Table.Column align="center">Phone Number</Table.Column>
          <Table.Column align="center">Email Address</Table.Column>
          <Table.Column align="center">Store Name</Table.Column>
          <Table.Column align="center">Transaction Totals (Local Currency)</Table.Column>
        </Table.Header>
        <Table.Body>
          {
            data.agregation.map((item: data) => (
              <Table.Row key={item.id}>
                <Table.Cell>{item.phone ? item.phone.split("-")[0] : "-"}</Table.Cell>
                <Table.Cell>{item.phone ? item.phone.split("-")[1] : "-"}</Table.Cell>
                <Table.Cell>{item.email ? item.email : "-"}</Table.Cell>
                <Table.Cell>{item.username}</Table.Cell>
                <Table.Cell>${item.total}</Table.Cell>
              </Table.Row>
            ))
          }
        </Table.Body>
      </Table>
      <Spacer y={1}/>
      <Container display="flex" justify="center" alignItems="center">
        <Pagination
          total={data.totalPages}
          page={Number(page)}
          initialPage={1}
          onChange={(page) => router.push(`/admin/merchants?page=${page}`)}
        />
      </Container>
      <Spacer y={1}/>
      <Container sm display="flex" alignItems="flex-end" justify="flex-end">
        <Text h3>
          Total Sum of Transactions: ${data.totalSum}
        </Text>
      </Container>
    </>
  );
}


export default function Buyers({fallback}: { fallback: any }) {
  const router = useRouter();
  const page = router.query.page || 1;
  return (
    <SWRConfig value={{fallback}}>
      <Head>
        <title>BulkMagic Buyers Dashboard</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <NavBar location={"buyers"}/>
      <Container sm>
        <Spacer y={1}/>
        <Text h1>Buyers Management</Text>
        <Text h2>Filters:</Text>
        <Spacer y={1}/>
        <Grid.Container gap={1} justify="center" alignItems="center">
          <Grid>
            <Container>
              <Row>
                <Checkbox.Group orientation="horizontal">
                  <Checkbox value="">
                    Country Code
                  </Checkbox>
                </Checkbox.Group>
                <Input size="sm" width="60px"/>
              </Row>
              <Text h5>
                (no need to include &#34;+&#34;)
              </Text>
            </Container>
          </Grid>
          <Grid>
            <Container>
              <Row>
                <Checkbox.Group orientation="horizontal">
                  <Checkbox value="">
                    Recent Signups
                  </Checkbox>
                </Checkbox.Group>
              </Row>
              <Text h5>
                (default is chronological)
              </Text>
            </Container>
          </Grid>
          <Grid>
            <Container>
              <Row>
                <Checkbox.Group orientation="horizontal">
                  <Checkbox value="">
                    Largest Transactions
                  </Checkbox>
                </Checkbox.Group>
              </Row>
              <Text h5>
                (try it to pair with &#34;Country Code&#34;)
              </Text>
            </Container>
          </Grid>
          <Grid>
            <Button>
              Search
            </Button>
          </Grid>
        </Grid.Container>
        <Spacer y={1}/>
        <DataTable page={page}/>
      </Container>
    </SWRConfig>
  )
}
