import Head from "next/head";
import NavBar from "@/components/navbar/Navbar";
import {Container, Text, Textarea, Button, Spacer, Pagination, Modal, Input, Link} from "@nextui-org/react";
import {useFormik} from "formik";
import {langCreate, langList, langSearch, langUpdate} from "@/utils/accessServices";
import {useEffect, useState} from "react";
import {useRouter} from "next/router";
import {toast} from "react-hot-toast";

export default function Languages() {
  const router = useRouter();

  const [visible, setVisible] = useState(false);

  const [form, setForm] = useState<any>({
    name: "",
    code: ""
  });

  const [lang, setLang] = useState<string>("en");
  const [langName, setLangName] = useState<string>("English");

  const [page, setPage] = useState<number>(1);
  // const languages: any = ({
  //   en: "English-en",
  //   // sq: "shqiptar",
  //   // ar: "العربية",
  //   // bn: "বাংলা",
  //   // ch: "中文",
  //   // nl: "Nederlandse",
  //   // fr: "Français",
  //   // de: "German",
  //   // gr: "ελληνική",
  //   // gu: "Avañe'ẽ",
  //   // hi: "हिंदुस्तानी",
  //   // it: "Italiano",
  //   // ko: "한국어",
  //   // ms: "Melayu",
  //   // fa: "پارسی",
  //   // pt: "Português",
  //   // ro: "Română",
  //   // ru: "русский",
  //   // sr: "Српско-хрватски",
  //   es: "Español-es"
  //   // sw: "Kiswahili",
  //   // sv: "Swedish",
  //   // ta: "தமிழ்",
  //   // tr: "Türk",
  // });
  const [languages, setLanguages] = useState<any>([]);
  const formik = useFormik({
    initialValues: {
      common: {},
      homeScreen: {},
      languageMenuScreen: {},
      loginMerchantScreen: {},
      signUpMerchantScreen: {},
      VerifyOtpScreen: {},
      editMerchantProfileScreen: {},
      loginBuyerScreen: {},
      signUpBuyerScreen: {},
      editBuyerProfileScreen: {},
      resultSearchScreen: {},
      ModalMenuComponent: {},
      ModalBuyerMenuComponent: {},
      dashboardScreen: {},
      dashboardBuyerScreen: {},
      createBulkVoucherScreen: {},
      editBulkVoucherScreen: {},
      vendorsPageScreen: {},
      itemsSellingScreen: {},
      paymentsConfirmScreen: {},
      paymentsConfirmBuyerScreen: {},
      salesRedemptionHistoryScreen: {},
      myVouchersScreen: {},
      scanRedemptionScreen: {},
      scanMerchantQrScreen: {},
      redemptionCodeScreen: {},
      voucherRedemptionScreen: {},
      voucherValidScreen: {},
      voucherInvalidScreen: {},
      forgotPasswordScreen: {},
      resetPasswordScreen: {},
      HowItWorksBuyerScreen: {},
      HowItWorksMerchantScreen: {},
      modalPhoto: {}
    },
    onSubmit: values => {
      langUpdate(langName, lang, values)
        .then(r => {
          console.log("entro submit", r);
        })
        .catch(e => console.log(e));
    }
  });

  const closeHandler = () => {
    setVisible(false);
  };

  const handleFormSubmit = () => {
    if (!form.name || !form.code) {
      toast.error("Please fill all the fields");
      return;
    }
    langCreate(form)
      .then(r => {
        toast.success("Language created successfully");
        console.log("entro submit", r);
        router.reload();
      })
      .catch(e => {
        console.log(e);
        toast.error(e.response.data.message || "Error creating language");
        setVisible(false);
        setForm({
          name: "",
          code: ""
        })
      });

  };

  const handleFormChange = (e: any) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value
    });
  };

  const handler = () => {
    // e.preventDefault();
    setVisible(true);
  };

  const handleLanguageChange = (e: any) => {
    e.preventDefault();
    let name = e.target.value.split("+")[0];
    let code = e.target.value.split("+")[1];
    router.push(`/admin/languages/${name}/${code}`)
  };

  useEffect(() => {
    if(!router.query.id) return;
    if(!router.query.lang) return;

    setLang(router.query.id as string);
    setLangName(router.query.lang as string)

    langList()
      .then(r => {
        console.log(r)
        setLanguages(r.data.langsArray);
      })
      .catch(e => console.log(e));

    langSearch(router.query.lang as string, router.query.id as string)
      .then(r => {
        console.log(`entro precarga de leng ${r?.data?.lang.name}-${r?.data?.lang?.code}`, r);
        formik.setValues(r?.data?.lang.sections);
      })
      .catch(e => console.log(e));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [router.query.name, router.query.id]);

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([JSON.stringify(formik?.values)], {type: "text/plain"});
    element.href = URL.createObjectURL(file);
    element.download = `${lang}.json`;
    document.body.appendChild(element);
    element.click();
  };


  return (
    <>
      <Head>
        <title>BulkMagic Languages Dashboard</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <NavBar location={"languages"}/>
      <Container sm aria-label={"test"}>
        <Container sm display="flex" alignItems={"center"} justify={"space-between"}>
          <h1>Languages</h1>
          <select onChange={(e) => handleLanguageChange(e)}>
            {
              languages?.map((lang: any) => {
                return (
                  // @ts-ignore
                  <option selected={lang === langName} key={lang} value={`${lang.name}+${lang.code}`}>{lang.name}</option>
                );
              })
            }
          </select>
          <Button onPress={() => handler()} color="warning">Add New Language</Button>
          <form style={{width: "100%"}} onSubmit={formik.handleSubmit}>
            {page === 1 && <Text h4 color="primary">Common</Text>}
            {
              page === 1 && Object?.entries(formik?.values?.common)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`common.${key}`}
                      name={`common.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 2 && <Text h4 color="primary">Home Screen</Text>}
            {
              page === 2 && Object?.entries(formik?.values?.homeScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`homeScreen.${key}`}
                      name={`homeScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 3 && <Text h4 color="primary">Language Menu Screen</Text>}
            {
              page === 3 && Object?.entries(formik?.values?.languageMenuScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`languageMenuScreen.${key}`}
                      name={`languageMenuScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 4 && <Text h4 color="primary">Login Merchant Screen</Text>}
            {
              page === 4 && Object?.entries(formik?.values?.loginMerchantScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`loginMerchantScreen.${key}`}
                      name={`loginMerchantScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 5 && <Text h4 color="primary">Sign Up Merchant Screen</Text>}
            {
              page === 5 && Object?.entries(formik?.values?.signUpMerchantScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`signUpMerchantScreen.${key}`}
                      name={`signUpMerchantScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 6 && <Text h4 color="primary">Verify Otp Screen</Text>}
            {
              page === 6 && Object?.entries(formik?.values?.VerifyOtpScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`VerifyOtpScreen.${key}`}
                      name={`VerifyOtpScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 7 && <Text h4 color="primary">Edit Merchant Profile Screen</Text>}
            {
              page === 7 && Object?.entries(formik?.values?.editMerchantProfileScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`editMerchantProfileScreen.${key}`}
                      name={`editMerchantProfileScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 8 && <Text h4 color="primary">Login Buyer Screen</Text>}
            {
              page === 8 && Object?.entries(formik?.values?.loginBuyerScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`loginBuyerScreen.${key}`}
                      name={`loginBuyerScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }

            {page === 9 && <Text h4 color="primary">Sign Up Buyer Screen</Text>}
            {
              page === 9 && Object?.entries(formik?.values?.signUpBuyerScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`signUpBuyerScreen.${key}`}
                      name={`signUpBuyerScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }

            {page === 10 && <Text h4 color="primary">Edit Buyer Profile Screen</Text>}
            {
              page === 10 && Object?.entries(formik?.values?.editBuyerProfileScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`editBuyerProfileScreen.${key}`}
                      name={`editBuyerProfileScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }

            {page === 11 && <Text h4 color="primary">Result Search Screen</Text>}
            {
              page === 11 && Object?.entries(formik?.values?.resultSearchScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`resultSearchScreen.${key}`}
                      name={`resultSearchScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }

            {page === 12 && <Text h4 color="primary">Modal Menu Component</Text>}
            {
              page === 12 && Object?.entries(formik?.values?.ModalMenuComponent)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`ModalMenuComponent.${key}`}
                      name={`ModalMenuComponent.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }

            {page === 13 && <Text h4 color="primary">Modal Buyer Menu Component</Text>}
            {
              page === 13 && Object?.entries(formik?.values?.ModalBuyerMenuComponent)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`ModalBuyerMenuComponent.${key}`}
                      name={`ModalBuyerMenuComponent.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 14 && <Text h4 color="primary">Dashboard Screen</Text>}
            {
              page === 14 && Object?.entries(formik?.values?.dashboardScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`dashboardScreen.${key}`}
                      name={`dashboardScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }

            {page === 15 && <Text h4 color="primary">Dashboard Buyer Screen</Text>}
            {
              page === 15 && Object?.entries(formik?.values?.dashboardBuyerScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`dashboardBuyerScreen.${key}`}
                      name={`dashboardBuyerScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }

            {page === 16 && <Text h4 color="primary">Create Bulk Voucher Screen</Text>}
            {
              page === 16 && Object?.entries(formik?.values?.createBulkVoucherScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`createBulkVoucherScreen.${key}`}
                      name={`createBulkVoucherScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 17 && <Text h4 color="primary">Vendors Page Screen</Text>}
            {
              page === 17 && Object?.entries(formik?.values?.vendorsPageScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`vendorsPageScreen.${key}`}
                      name={`vendorsPageScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 18 && <Text h4 color="primary">Items Selling Screen</Text>}
            {
              page === 18 && Object?.entries(formik?.values?.itemsSellingScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`itemsSellingScreen.${key}`}
                      name={`itemsSellingScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 19 && <Text h4 color="primary">Payments Confirm Screen</Text>}
            {
              page === 19 && Object?.entries(formik?.values?.paymentsConfirmScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`paymentsConfirmScreen.${key}`}
                      name={`paymentsConfirmScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 20 && <Text h4 color="primary">Payments Confirm Buyer Screen</Text>}
            {
              page === 20 && Object?.entries(formik?.values?.paymentsConfirmBuyerScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`paymentsConfirmBuyerScreen.${key}`}
                      name={`paymentsConfirmBuyerScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 21 && <Text h4 color="primary">Sales Redemption History Screen</Text>}
            {
              page === 21 && Object?.entries(formik?.values?.salesRedemptionHistoryScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`salesRedemptionHistoryScreen.${key}`}
                      name={`salesRedemptionHistoryScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 22 && <Text h4 color="primary">My Vouchers Screen</Text>}
            {
              page === 22 && Object?.entries(formik?.values?.myVouchersScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`myVouchersScreen.${key}`}
                      name={`myVouchersScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 23 && <Text h4 color="primary">Scan Redemption Screen</Text>}
            {
              page === 23 && Object?.entries(formik?.values?.scanRedemptionScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`scanRedemptionScreen.${key}`}
                      name={`scanRedemptionScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 24 && <Text h4 color="primary">Scan Merchant Qr Screen</Text>}
            {
              page === 24 && Object?.entries(formik?.values?.scanMerchantQrScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`scanMerchantQrScreen.${key}`}
                      name={`scanMerchantQrScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 25 && <Text h4 color="primary">Redemption Code Screen</Text>}
            {
              page === 25 && Object?.entries(formik?.values?.redemptionCodeScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`redemptionCodeScreen.${key}`}
                      name={`redemptionCodeScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 26 && <Text h4 color="primary">Voucher Redemption Screen</Text>}
            {
              page === 26 && Object?.entries(formik?.values?.voucherRedemptionScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`voucherRedemptionScreen.${key}`}
                      name={`voucherRedemptionScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 27 && <Text h4 color="primary">Voucher Valid Screen</Text>}
            {
              page === 27 && Object?.entries(formik?.values?.voucherValidScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`voucherValidScreen.${key}`}
                      name={`voucherValidScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 28 && <Text h4 color="primary">Voucher Invalid Screen</Text>}
            {
              page === 28 && Object?.entries(formik?.values?.voucherInvalidScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`voucherInvalidScreen.${key}`}
                      name={`voucherInvalidScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 29 && <Text h4 color="primary">Forgot Password Screen</Text>}
            {
              page === 29 && Object?.entries(formik?.values?.forgotPasswordScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`forgotPasswordScreen.${key}`}
                      name={`forgotPasswordScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 30 && <Text h4 color="primary">Reset Password Screen</Text>}
            {
              page === 30 && Object?.entries(formik?.values?.resetPasswordScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`resetPasswordScreen.${key}`}
                      name={`resetPasswordScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 31 && <Text h4 color="primary">How It Works Buyer Screen</Text>}
            {
              page === 31 && Object?.entries(formik?.values?.HowItWorksBuyerScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`HowItWorksBuyerScreen.${key}`}
                      name={`HowItWorksBuyerScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 32 && <Text h4 color="primary">How It Works Merchant Screen</Text>}
            {
              page === 32 && Object?.entries(formik?.values?.HowItWorksMerchantScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`HowItWorksMerchantScreen.${key}`}
                      name={`HowItWorksMerchantScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {page === 33 && <Text h4 color="primary">Photo Modal</Text>}
            {
              page === 33 && Object?.entries(formik?.values?.modalPhoto)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`HowItWorksMerchantScreen.${key}`}
                      name={`HowItWorksMerchantScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            {
              page === 34 && Object?.entries(formik?.values?.editBulkVoucherScreen)?.map(([key, value]) => {
                return (
                  <div key={key}>
                    <Text h6>{key}</Text>
                    <Textarea
                      key={key}
                      fullWidth
                      id={`HowItWorksMerchantScreen.${key}`}
                      name={`HowItWorksMerchantScreen.${key}`}
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      // @ts-ignore
                      value={value}
                    />
                    <Spacer y={1}/>
                  </div>
                );
              })
            }
            <Pagination total={34} initialPage={1} onChange={(e) => setPage(e)}/>
            <Spacer y={1}/>
            <Button type="submit">
              Save
            </Button>
            <Spacer y={1}/>
            <Button color={"success"} onPress={() => handleDownload()}>
              Download JSON
            </Button>
          </form>
        </Container>
      </Container>
      <Modal
        closeButton
        blur
        aria-labelledby="modal-title"
        open={visible}
        onClose={closeHandler}>
        <Modal.Header>
          <Text h3>You want to add a new language to the list?</Text>
        </Modal.Header>
        <Modal.Body>
          <Text>If you are sure, please complete the fields </Text>
          <Input
            bordered
            name={"name"}
            onChange={(e) => handleFormChange(e)}
            fullWidth
            clearable
            label={"Name"}
            placeholder={"English"}/>
          <Input
            bordered
            name={"code"}
            onChange={(e) => handleFormChange(e)}
            fullWidth
            clearable
            label={"ISO 639-1 standard language code"}
            placeholder={"en"}/>
          <Link block isExternal href="https://www.andiamo.co.uk/resources/iso-language-codes/"> List of ISO 639-1
            standard language codes </Link>
        </Modal.Body>
        <Modal.Footer>
          <Button auto flat color="error" onPress={closeHandler}>
            Close
          </Button>
          <Button color="success" auto onPress={handleFormSubmit}>
            Add language
          </Button>
        </Modal.Footer>
      </Modal>
    </>
  );
}

//      editBulkVoucherScreen: {
//         type: Object
//       },
