import Head from "next/head";
import NavBar from "@/components/navbar/Navbar";
import {Container, Table, Text, Spacer, Input, Modal, Button } from "@nextui-org/react";
import {useEffect, useState} from "react";
import {useRouter} from "next/router";
import PhoneInput from 'react-phone-input-2'
import 'react-phone-input-2/lib/high-res.css'
export default function Admin() {
  const router = useRouter();
  const [form, setForm] = useState({
    email: "",
    phone: "",
    password: "",
  });

  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const user = localStorage.getItem("user");
    if (!user) {
      router.push("/");
    } else {
      return;
    }
  }, [router]);

  const handleFormSubmit = () => {
  };

  const handleFormChange = (e: any) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value
    });
  };

  const closeHandler = () => {
    setVisible(false);
    console.log("closed");
  };

  const handler = () => setVisible(true);

  return (
    <>
      <Head>
        <title>BulkMagic Admin Dashboard</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <NavBar location={"admin"}/>
      <Container sm>
        <Spacer y={1}/>
        <Container display="flex" alignItems="center" justify="space-between">
          <Text h1>Admin</Text>
          <Button auto onPress={handler} color="success">
            Create Admin
          </Button>
        </Container>
          <Modal
            closeButton
            blur
            aria-labelledby="modal-title"
            open={visible}
            onClose={closeHandler}>
            <Modal.Header>
              <Text h2>Lets Create an Admin</Text>
            </Modal.Header>
            <Modal.Body>
              <Input
                bordered
                name={"name"}
                onChange={(e) => handleFormChange(e)}
                fullWidth
                clearable
                label={"Name"}/>
              <Text>
                Phone Number
              </Text>
              <PhoneInput
                inputStyle={{
                  border: '2px solid #d9d9d9',
                  borderRadius: '15px',
                  width: '100%',
                  background: 'white',
                  fontWeight: '400',
                  height: '45px',
                  fontSize: '14px',
                }}
                buttonStyle={{
                  border: '2px solid #d9d9d9',
                  borderRadius: '15px 0 0 15px',
                }}
                country='us'
                inputProps={{
                  name: 'phone',
                  required: true,
                  autoFocus: true
                }}
                autoFormat={false}
                onChange={(e) => handleFormChange(e)}
              />
              <Input
                bordered
                name={"email"}
                onChange={(e) => handleFormChange(e)}
                fullWidth
                clearable
                label={"Email"}/>
              <Input.Password
                bordered
                name={"password"}
                onChange={(e) => handleFormChange(e)}
                fullWidth
                clearable
                label={"Password"}/>
            <Spacer y={2}/>
            </Modal.Body>
            <Modal.Footer>
              <Button auto flat color="error" onPress={closeHandler}>
                Close
              </Button>
              <Button auto onPress={handleFormSubmit}>
                Create
              </Button>
            </Modal.Footer>
          </Modal>
        <Spacer y={1}/>
        <Table
          lined
          color="primary"
          aria-label="Example pagination table2"
          css={{
            height: "auto",
            minWidth: "100%",
          }}>
          <Table.Header>
            <Table.Column align="center">Country Code</Table.Column>
            <Table.Column align="center">Phone Number</Table.Column>
            <Table.Column align="center">Email Address</Table.Column>
            <Table.Column align="center">Name</Table.Column>
          </Table.Header>
          <Table.Body>
            <Table.Row key="1">
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>marcelo.godoy@mi.unc.edu.ar</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
            </Table.Row>
            <Table.Row key="2">
              <Table.Cell>+54</Table.Cell>
              <Table.Cell>3517630330</Table.Cell>
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
            </Table.Row>
            <Table.Row key="3">
              <Table.Cell>+54</Table.Cell>
              <Table.Cell>3517630330</Table.Cell>
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
            </Table.Row>
            <Table.Row key="4">
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>N/A</Table.Cell>
              <Table.Cell>marcelo.godoy@mi.unc.edu.ar</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
            </Table.Row>
            <Table.Row key="5">
              <Table.Cell>+54</Table.Cell>
              <Table.Cell>3517630330</Table.Cell>
              <Table.Cell>marcelo.godoy@mi.unc.edu.ar</Table.Cell>
              <Table.Cell>Marcelo Store</Table.Cell>
            </Table.Row>
          </Table.Body>
        </Table>
      </Container>
    </>
  );
}

