import Head from "next/head";
import NavBar from "@/components/navbar/Navbar";
import {Container, Text, Spacer} from "@nextui-org/react";
import CreateAdminModal from "@/components/modal/createAdmin/CreateAdminModal";
import AdminsTable from "@/components/table/adminsTable/AdminsTable";


export default function Admin() {
  return (
    <>
      <Head>
        <title>BulkMagic Admin Dashboard</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <NavBar location={"admin"}/>
      <Container sm>
        <Spacer y={1}/>
        <Container display="flex" alignItems="center" justify="space-between">
          <Text h1>Admin</Text>
          <CreateAdminModal/>
        </Container>
        <Spacer y={1}/>
        <AdminsTable/>
      </Container>
    </>
  );
}

